---

- name: Create destination folder
  file:
    path: /opt/kafka-manager
    state: directory

- name: Unzip build to destination folder
  unarchive:
    src: http://nexus.navent.biz:8081/nexus/content/repositories/releases/com/yahoo/kafka-manager/{{kafka_manager_version}}/kafka-manager-{{kafka_manager_version}}.zip
    dest: /opt/kafka-manager
    remote_src: True

- name: Set config file parameters
  template: src=application.conf.j2 dest=/opt/kafka-manager/kafka-manager-{{kafka_manager_version}}/conf/application.conf

- name: start kafka-manager
  shell: nohup /opt/kafka-manager/kafka-manager-{{kafka_manager_version}}/bin/kafka-manager &

